# This workflow will build a golang project
# The point of this is to test that the project
# can build, rather than to actually publish a
# build.
#
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    tags:
      - 'v*'
  pull_request:
    types: [opened, synchronize]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.13'

    - name: Build Linux
      run: go build -v -o "${{github.workspace}}/deezerdl-x64" "${{github.workspace}}/cmd/deezerdl.go"
